### ISSUE TITLE
isbox?

### ISSUE THREAD

**Issue by maidenone** [galou/freecad.workbench_ros#10]
from deep_copy.py
```python
elif (is_box(obj) or is_box(obj)
``` 
copy-paste typo?

Reviewing from my phone, will see if i can get it running on my computer tomorrow, then i might be able to create "better" issues/PR.

**Comment by galou** [comment]
Thanks! Fixed in 2bfeb4a.

Please don't be scared, you'll find a lot of bugs. I'm still struggling to find an appropriate type to base my custom FreeCAD objects from. The current state is that I have an object that behaves like a place-able group but the elements of the group are outside of it on document restore (a recompute fixes the issue, I need to test if adding `recompute` in `onDocumentRestored` helps).
